[project]
name = "sql-ai-chatbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-community>=0.4.1",
    "langchain-core>=1.1.0",
    "openai>=2.8.1",
    "python-dotenv>=1.2.1",
]
